/*
 * This file is generated by jOOQ.
*/
package com.db.tables.daos;


import com.db.tables.MUsers;
import com.db.tables.records.MUsersRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class MUsersDao extends DAOImpl<MUsersRecord, com.db.tables.pojos.MUsers, String> {

    /**
     * Create a new MUsersDao without any configuration
     */
    public MUsersDao() {
        super(MUsers.M_USERS, com.db.tables.pojos.MUsers.class);
    }

    /**
     * Create a new MUsersDao with an attached configuration
     */
    @Autowired
    public MUsersDao(Configuration configuration) {
        super(MUsers.M_USERS, com.db.tables.pojos.MUsers.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.db.tables.pojos.MUsers object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db.tables.pojos.MUsers> fetchById(String... values) {
        return fetch(MUsers.M_USERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db.tables.pojos.MUsers fetchOneById(String value) {
        return fetchOne(MUsers.M_USERS.ID, value);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.db.tables.pojos.MUsers> fetchByUsername(String... values) {
        return fetch(MUsers.M_USERS.USERNAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.db.tables.pojos.MUsers> fetchByPassword(String... values) {
        return fetch(MUsers.M_USERS.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>authority IN (values)</code>
     */
    public List<com.db.tables.pojos.MUsers> fetchByAuthority(String... values) {
        return fetch(MUsers.M_USERS.AUTHORITY, values);
    }

    /**
     * Fetch records that have <code>sex IN (values)</code>
     */
    public List<com.db.tables.pojos.MUsers> fetchBySex(String... values) {
        return fetch(MUsers.M_USERS.SEX, values);
    }

    /**
     * Fetch records that have <code>delete_flg IN (values)</code>
     */
    public List<com.db.tables.pojos.MUsers> fetchByDeleteFlg(String... values) {
        return fetch(MUsers.M_USERS.DELETE_FLG, values);
    }
}
