/*
 * This file is generated by jOOQ.
*/
package com.db.tables.records;


import com.db.tables.MFiles;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MFilesRecord extends UpdatableRecordImpl<MFilesRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1667280143;

    /**
     * Setter for <code>milk.m_files.id</code>. 主键
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>milk.m_files.id</code>. 主键
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>milk.m_files.file_name</code>. 文件名称
     */
    public void setFileName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>milk.m_files.file_name</code>. 文件名称
     */
    public String getFileName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>milk.m_files.file_url</code>. 文件地址
     */
    public void setFileUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>milk.m_files.file_url</code>. 文件地址
     */
    public String getFileUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>milk.m_files.username</code>. 用户名
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>milk.m_files.username</code>. 用户名
     */
    public String getUsername() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MFiles.M_FILES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MFiles.M_FILES.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MFiles.M_FILES.FILE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MFiles.M_FILES.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFileUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MFilesRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MFilesRecord value2(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MFilesRecord value3(String value) {
        setFileUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MFilesRecord value4(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MFilesRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MFilesRecord
     */
    public MFilesRecord() {
        super(MFiles.M_FILES);
    }

    /**
     * Create a detached, initialised MFilesRecord
     */
    public MFilesRecord(String id, String fileName, String fileUrl, String username) {
        super(MFiles.M_FILES);

        set(0, id);
        set(1, fileName);
        set(2, fileUrl);
        set(3, username);
    }
}
