server:
    port: 8080

spring:
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:mysql://localhost:3306/milk
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jooq:
    sql-dialect: mysql
  mail:
    host: smtp.163.com
    port: 465
    username: xiaogm1226@163.com
    password: 15851146830qaz
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
logging:
  file: logs/log.log


c_milk:
  base-upload-path: /pic


