server:
    port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/milk?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jooq:
    sql-dialect: mysql

