server:
    port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/milk
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jooq:
    sql-dialect: mysql
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html


