/*
 * This file is generated by jOOQ.
*/
package com.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MFiles implements Serializable {

    private static final long serialVersionUID = -695792129;

    private String id;
    private String fileName;
    private String fileUrl;
    private String username;

    public MFiles() {}

    public MFiles(MFiles value) {
        this.id = value.id;
        this.fileName = value.fileName;
        this.fileUrl = value.fileUrl;
        this.username = value.username;
    }

    public MFiles(
        String id,
        String fileName,
        String fileUrl,
        String username
    ) {
        this.id = id;
        this.fileName = fileName;
        this.fileUrl = fileUrl;
        this.username = username;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileUrl() {
        return this.fileUrl;
    }

    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MFiles (");

        sb.append(id);
        sb.append(", ").append(fileName);
        sb.append(", ").append(fileUrl);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
