/*
 * This file is generated by jOOQ.
*/
package com.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MUsers implements Serializable {

    private static final long serialVersionUID = -1739560945;

    private String id;
    private String username;
    private String password;
    private String authority;
    private String sex;
    private String deleteFlg;

    public MUsers() {}

    public MUsers(MUsers value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.authority = value.authority;
        this.sex = value.sex;
        this.deleteFlg = value.deleteFlg;
    }

    public MUsers(
        String id,
        String username,
        String password,
        String authority,
        String sex,
        String deleteFlg
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.authority = authority;
        this.sex = sex;
        this.deleteFlg = deleteFlg;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getAuthority() {
        return this.authority;
    }

    public void setAuthority(String authority) {
        this.authority = authority;
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getDeleteFlg() {
        return this.deleteFlg;
    }

    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MUsers (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(authority);
        sb.append(", ").append(sex);
        sb.append(", ").append(deleteFlg);

        sb.append(")");
        return sb.toString();
    }
}
